import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");
const dataDir =
  process.env.PORTFOLIO_DATA_DIR?.trim() ||
  process.env.RENDER_DISK_MOUNT_PATH?.trim() ||
  path.join(root, "data");
const inputPath = path.join(dataDir, "asset-names.json");
const outputDir = path.join(root, "src", "lib", "assets");
const outputPath = path.join(outputDir, "assetName.js");
const declarationPath = path.join(outputDir, "assetName.d.ts");

if (!fs.existsSync(inputPath)) {
  throw new Error(`Missing ${inputPath}. Run scripts/fetch_asset_names.py first.`);
}

const names = JSON.parse(fs.readFileSync(inputPath, "utf8"));
const sortedNames = Object.fromEntries(
  Object.entries(names).sort(([left], [right]) => left.localeCompare(right))
);

fs.mkdirSync(outputDir, { recursive: true });
fs.writeFileSync(
  outputPath,
  `// This file is generated by npm run update-assets. Do not edit manually.\n\nexport const ASSET_NAMES = Object.freeze(${JSON.stringify(
    sortedNames,
    null,
    2
  )});\n`,
  "utf8"
);
fs.writeFileSync(
  declarationPath,
  "export const ASSET_NAMES: Readonly<Record<string, string>>;\n",
  "utf8"
);

console.log(`Generated ${outputPath}`);
